/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frameak;

import exekutagarriak.EuskalSelekzioa;
import exekutagarriak.EuskalSelekzioaMenua;

import java.time.LocalDate;
import java.util.ArrayList;
import model.*;
import exekutagarriak.*;
import static exekutagarriak.EuskalSelekzioaMenua.selekzioa;
import java.awt.Color;


/**
 *
 * @author arceredillo.adrian
 */
public class partidakAntolatu extends javax.swing.JFrame {
    
    public static ArrayList<IntegranteSeleccion> seleccion = new ArrayList<IntegranteSeleccion>();
    public static ArrayList<Futbolista> futbolistasSeleccion = new ArrayList<Futbolista>(); //arrayList que contiene solamente elementos del tipo FUTBOLISTA
    public static int cantidadJugadoresTarjeta = 0;
    
    ArrayList<Futbolista> jugadoresTodasLasTarjetas = new ArrayList<Futbolista>();    //arrayList que guardará los nombres de todos los jugadores amonestados (CON REPETIDOS)
    /**
     * Creates new form partidakAntolatu
     */
    public partidakAntolatu() {
        initComponents();
        
        InfoJugadores.setLineWrap(true);
        PlantillaGeneral.setLineWrap(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        ElegirRandomPonerT = new javax.swing.JLabel();
        RandomPlayerAdd = new javax.swing.JButton();
        VerNombresJugadores = new javax.swing.JLabel();
        VerPlantillaNombres = new javax.swing.JLabel();
        CrearPlantilla = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoJugadores = new javax.swing.JTextArea();
        RegistroTarjetas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        PlantillaGeneral = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTitulo.setText("PARTIDA BAT ANTOLATU");

        ElegirRandomPonerT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ElegirRandomPonerT.setText("add player");
        ElegirRandomPonerT.setToolTipText("");

        RandomPlayerAdd.setText("Random Player");
        RandomPlayerAdd.setActionCommand("");
        RandomPlayerAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomPlayerAddActionPerformed(evt);
            }
        });

        VerNombresJugadores.setText("Plantilla Osoa: ");

        VerPlantillaNombres.setText("aaa");

        CrearPlantilla.setText("Sortu");
        CrearPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearPlantillaActionPerformed(evt);
            }
        });

        InfoJugadores.setColumns(20);
        InfoJugadores.setRows(5);
        InfoJugadores.setText("Información del jugador: ");
        jScrollPane1.setViewportView(InfoJugadores);

        RegistroTarjetas.setText("Todas las tarjetas");
        RegistroTarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroTarjetasActionPerformed(evt);
            }
        });

        PlantillaGeneral.setColumns(20);
        PlantillaGeneral.setRows(5);
        PlantillaGeneral.setText("Toda la plantilla");
        jScrollPane2.setViewportView(PlantillaGeneral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VerNombresJugadores)
                        .addGap(18, 18, 18)
                        .addComponent(CrearPlantilla)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(VerPlantillaNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RegistroTarjetas)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ElegirRandomPonerT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RandomPlayerAdd)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(148, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(RegistroTarjetas))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VerNombresJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrearPlantilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(VerPlantillaNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(ElegirRandomPonerT)
                .addGap(18, 18, 18)
                .addComponent(RandomPlayerAdd)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RandomPlayerAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandomPlayerAddActionPerformed
        // TODO add your handling code here:
        
        int jugadorAleatorio = (int) (Math.random() * futbolistasSeleccion.size());
        
        //PlantillaGeneral
        
        InfoJugadores.setText(InfoJugadores.getText() + "Jugador: " + ++cantidadJugadoresTarjeta + "\n" + 
                "   - Nombre: " + new String(futbolistasSeleccion.get(jugadorAleatorio).getNombre()) + " " + new String(futbolistasSeleccion.get(jugadorAleatorio).getApellidos()) + "\n" + 
                "   - Dorsal: " + futbolistasSeleccion.get(jugadorAleatorio).getDorsal() + "    /   Posición: " + futbolistasSeleccion.get(jugadorAleatorio).getDemarcacion() + "\n" + 
                "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n");
        jugadoresTodasLasTarjetas.add(futbolistasSeleccion.get(jugadorAleatorio));
        
        System.out.println(jugadoresTodasLasTarjetas);
        
        
        //arrayList-s para el control de tarjetas ()
        
        InfoJugadores.setEnabled(true);
        
        
        
    }//GEN-LAST:event_RandomPlayerAddActionPerformed

    private void CrearPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearPlantillaActionPerformed
        // TODO add your handling code here:
        
        
        seleccion = EuskalSelekzioaMenua.selekzioa;  //al arrayList "seleccion", asignarle el contenido del arrayList creado en "EuskalSelekzioa"
        System.out.println(seleccion);
        
        int contarJugadores = 0;
        for (int i = 0; i < seleccion.size(); ++i) {
            if (seleccion.get(i).getClass() == Futbolista.class) {
                //jugadoresSeleccion.add(seleccion.get(i));
                System.out.println(seleccion.get(i));
                futbolistasSeleccion.add((Futbolista) seleccion.get(i));
                ++contarJugadores;
            }
        }
        
        System.out.println("--------------------------");
        
        VerPlantillaNombres.setText("");
        for (int i = 0; i < futbolistasSeleccion.size(); ++i) {
            String nombrePlayer = futbolistasSeleccion.get(i).getNombre() + " " + futbolistasSeleccion.get(i).getApellidos() + ", ";
            //VerPlantillaNombres.setText(VerPlantillaNombres.getText() + futbolistasSeleccion.get(i).getNombre() + " " + futbolistasSeleccion.get(i).getApellidos() + ", <br>");
            VerPlantillaNombres.setText(VerPlantillaNombres.getText() + nombrePlayer);
            
        }
        
        RandomPlayerAdd.setEnabled(true);
        InfoJugadores.setText("");  //vaciar la caja de texto de jugadores random (= jugadores que recibirán tarjeta)
        //VerPlantillaNombres.setText("fff");
        
        
        PlantillaGeneral.setEnabled(true);
        PlantillaGeneral.setSelectedTextColor(Color.red);
        PlantillaGeneral.setText("");
        
        for (int i = 0; i < selekzioa.size(); ++i) {
            PlantillaGeneral.setText(PlantillaGeneral.getText() + "Jugador: " + ++cantidadJugadoresTarjeta + "\n" + 
                selekzioa.get(i) + " " /*+ new String(selekzioa.get(i).getApellidos())*/ + "\n" + 
                "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n");
        }
        
        
    }//GEN-LAST:event_CrearPlantillaActionPerformed

    private void RegistroTarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroTarjetasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RegistroTarjetasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(partidakAntolatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(partidakAntolatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(partidakAntolatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(partidakAntolatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new partidakAntolatu().setVisible(true);
                RandomPlayerAdd.setEnabled(false);  //bloquear el botón "RandomPlayerAdd" según se ejecute el frame
                InfoJugadores.setEnabled(false);
                PlantillaGeneral.setEnabled(false);
            }
        });
        
        //seleccion = EuskalSelekzioa.selekzioa;  //prueba 1
        EuskalSelekzioaMenua.selekzioarenPlantillaOsoaSortu();
        
        EuskalSelekzioaMenua.taldekatuta2(selekzioa);
        //EuskalSelekzioa.selekzioOsoaSortu();
        
        
        
        
        
        Partida par1 = new Partida();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton CrearPlantilla;
    public static javax.swing.JLabel ElegirRandomPonerT;
    public static javax.swing.JTextArea InfoJugadores;
    public static javax.swing.JTextArea PlantillaGeneral;
    public static javax.swing.JButton RandomPlayerAdd;
    private javax.swing.JButton RegistroTarjetas;
    public static javax.swing.JLabel VerNombresJugadores;
    public static javax.swing.JLabel VerPlantillaNombres;
    public static javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
