/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frameak;

import exekutagarriak.EuskalSelekzioa;
import exekutagarriak.EuskalSelekzioaMenua;

import java.time.LocalDate;
import java.util.ArrayList;
import model.*;
import exekutagarriak.*;
import static exekutagarriak.EuskalSelekzioaMenua.selekzioa;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JFrame;


/**
 *
 * @author arceredillo.adrian
 */
public class partidakAntolatu extends javax.swing.JFrame {
    
    public static ArrayList<IntegranteSeleccion> seleccion = new ArrayList<IntegranteSeleccion>();
    public static ArrayList<Futbolista> futbolistasSeleccion = new ArrayList<Futbolista>(); //arrayList que contiene solamente elementos del tipo FUTBOLISTA
    public static int cantidadJugadoresTarjeta = 0;
    
    public static ArrayList<Futbolista> jugadoresTodasLasTarjetas = new ArrayList<Futbolista>();    //arrayList que guardará los nombres de todos los jugadores amonestados (CON REPETIDOS)
    public static ArrayList<Masajista> niJugadorNiEntrenador = new ArrayList<Masajista>();  //arrayList para separar los de tipo Masajista (Fisioterapeuta y Médico)
    /**
     * Creates new form partidakAntolatu
     */
    public partidakAntolatu() {
        this.setTitle("Partidak Antolatu - Adrian");
        this.setPreferredSize(new Dimension(1000, 900));
        initComponents();
        
        InfoJugadores.setLineWrap(true);
        PlantillaJugadores.setLineWrap(true);
        PlantillaEntrenadores.setLineWrap(true);
        PlantillaMedicos.setLineWrap(true);
        PlantillaOtros.setLineWrap(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        ElegirRandomPonerT = new javax.swing.JLabel();
        RandomPlayerAdd = new javax.swing.JButton();
        VerNombresJugadores = new javax.swing.JLabel();
        VerPlantillaNombres = new javax.swing.JLabel();
        CrearPlantilla = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoJugadores = new javax.swing.JTextArea();
        RegistroTarjetas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        PlantillaJugadores = new javax.swing.JTextArea();
        FiltroJugadores = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        PlantillaEntrenadores = new javax.swing.JTextArea();
        FiltroEntrenadores = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        PlantillaMedicos = new javax.swing.JTextArea();
        FiltroMedicos = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        PlantillaOtros = new javax.swing.JTextArea();
        FiltroOtros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTitulo.setText("PARTIDA BAT ANTOLATU");

        ElegirRandomPonerT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ElegirRandomPonerT.setText("add player");
        ElegirRandomPonerT.setToolTipText("");

        RandomPlayerAdd.setText("Random Player");
        RandomPlayerAdd.setActionCommand("");
        RandomPlayerAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomPlayerAddActionPerformed(evt);
            }
        });

        VerNombresJugadores.setText("Plantilla Osoa: ");

        VerPlantillaNombres.setText("aaa");

        CrearPlantilla.setText("Sortu");
        CrearPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearPlantillaActionPerformed(evt);
            }
        });

        InfoJugadores.setColumns(20);
        InfoJugadores.setRows(5);
        InfoJugadores.setText("Información del jugador: ");
        jScrollPane1.setViewportView(InfoJugadores);

        RegistroTarjetas.setText("Todas las tarjetas");
        RegistroTarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroTarjetasActionPerformed(evt);
            }
        });

        PlantillaJugadores.setColumns(20);
        PlantillaJugadores.setRows(5);
        PlantillaJugadores.setText("Informacion del personal");
        jScrollPane2.setViewportView(PlantillaJugadores);

        FiltroJugadores.setText("Jugadores: ");

        PlantillaEntrenadores.setColumns(20);
        PlantillaEntrenadores.setRows(5);
        PlantillaEntrenadores.setText("Informacion del personal");
        jScrollPane3.setViewportView(PlantillaEntrenadores);

        FiltroEntrenadores.setText("Entrenadores: ");

        PlantillaMedicos.setColumns(20);
        PlantillaMedicos.setRows(5);
        PlantillaMedicos.setText("Informacion del personal");
        jScrollPane4.setViewportView(PlantillaMedicos);

        FiltroMedicos.setText("Medicos: ");

        PlantillaOtros.setColumns(20);
        PlantillaOtros.setRows(5);
        PlantillaOtros.setText("Informacion del personal");
        jScrollPane5.setViewportView(PlantillaOtros);

        FiltroOtros.setText("Otros: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(VerNombresJugadores)
                                .addGap(18, 18, 18)
                                .addComponent(CrearPlantilla)
                                .addGap(18, 18, 18)
                                .addComponent(VerPlantillaNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(FiltroJugadores))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RandomPlayerAdd)
                            .addComponent(ElegirRandomPonerT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegistroTarjetas))
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FiltroOtros)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane5)
                            .addComponent(FiltroMedicos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(FiltroEntrenadores, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(RegistroTarjetas))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VerNombresJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrearPlantilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VerPlantillaNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ElegirRandomPonerT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RandomPlayerAdd)
                .addGap(11, 11, 11)
                .addComponent(FiltroJugadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(FiltroEntrenadores)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FiltroMedicos)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FiltroOtros)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RandomPlayerAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandomPlayerAddActionPerformed
        // TODO add your handling code here:
        
        int jugadorAleatorio = (int) (Math.random() * futbolistasSeleccion.size());
        
        //PlantillaGeneral
        
        InfoJugadores.setText(InfoJugadores.getText() + "Jugador: " + ++cantidadJugadoresTarjeta + "\n" + 
                "   - Nombre: " + new String(futbolistasSeleccion.get(jugadorAleatorio).getNombre()) + " " + new String(futbolistasSeleccion.get(jugadorAleatorio).getApellidos()) + "\n" + 
                "   - Dorsal: " + futbolistasSeleccion.get(jugadorAleatorio).getDorsal() + "    /   Posición: " + futbolistasSeleccion.get(jugadorAleatorio).getDemarcacion() + "\n" + 
                "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n");
        jugadoresTodasLasTarjetas.add(futbolistasSeleccion.get(jugadorAleatorio));
        
        System.out.println(jugadoresTodasLasTarjetas);
        
        
        //arrayList-s para el control de tarjetas ()
        
        InfoJugadores.setEnabled(true);
        
        
        
    }//GEN-LAST:event_RandomPlayerAddActionPerformed

    private void CrearPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearPlantillaActionPerformed
        // TODO add your handling code here:
        
        seleccion = EuskalSelekzioaMenua.selekzioa;  //al arrayList "seleccion", asignarle el contenido del arrayList creado en "EuskalSelekzioa"
        System.out.println(seleccion);
        
        int contarJugadores = 0;
        for (int i = 0; i < seleccion.size(); ++i) {
            if (seleccion.get(i).getClass() == Futbolista.class) {
                //jugadoresSeleccion.add(seleccion.get(i));
                System.out.println(seleccion.get(i));
                futbolistasSeleccion.add((Futbolista) seleccion.get(i));
                ++contarJugadores;
            }
        }
        
        System.out.println("--------------------------");
        
        VerPlantillaNombres.setText("");
        for (int i = 0; i < futbolistasSeleccion.size(); ++i) {
            String nombrePlayer = futbolistasSeleccion.get(i).getNombre() + " " + futbolistasSeleccion.get(i).getApellidos() + ", ";
            //VerPlantillaNombres.setText(VerPlantillaNombres.getText() + futbolistasSeleccion.get(i).getNombre() + " " + futbolistasSeleccion.get(i).getApellidos() + ", <br>");
            VerPlantillaNombres.setText(VerPlantillaNombres.getText() + nombrePlayer);
            
        }
        
        RandomPlayerAdd.setEnabled(true);
        InfoJugadores.setText("");  //vaciar la caja de texto de jugadores random (= jugadores que recibirán tarjeta)
        //VerPlantillaNombres.setText("fff");
        
        //todos los tipo Futbolista
        PlantillaJugadores.setText("");
        PlantillaJugadores.setEnabled(true);
        PlantillaJugadores.setSelectedTextColor(Color.white);   //PlantillaJugadores.setText("");
        
        //todos los tipo Entrenador
        PlantillaEntrenadores.setText("");
        PlantillaEntrenadores.setEnabled(true);
        PlantillaEntrenadores.setSelectedTextColor(Color.white);    //PlantillaEntrenadores.setText("");
        
        //todos los tipo Masajista (FISIOTERAPEUTA)
        PlantillaMedicos.setText("");
        PlantillaMedicos.setEnabled(true);
        PlantillaMedicos.setSelectedTextColor(Color.white);     //PlantillaMedicos.setText("");
        
        //todos los tipo Masajista (MÉDICO)
        PlantillaOtros.setText("");
        PlantillaOtros.setEnabled(true);
        PlantillaOtros.setSelectedTextColor(Color.white);   //PlantillaOtros.setText("");
        
        
        //filtrar por tipo Futbolista
        for (int i = 0; i < selekzioa.size(); ++i) {
            if (selekzioa.get(i).getClass() == Futbolista.class) {    //los tipo Futbolistas
                
                PlantillaJugadores.setText(PlantillaJugadores.getText() + "Integrante: " + ++cantidadJugadoresTarjeta + "\n" + 
                        selekzioa.get(i) + "\n" + "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n");
            }
        }
        
        //filtrar por tipo Entrenador
        for (int i = 0; i < selekzioa.size(); ++i) {
            if (selekzioa.get(i).getClass() == Entrenador.class) {    //los tipo Futbolistas
                
                PlantillaEntrenadores.setText(PlantillaEntrenadores.getText() + "Integrante: " + ++cantidadJugadoresTarjeta + "\n" + 
                        selekzioa.get(i) + "\n" + "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n");
            }
        }
        
        //filtrar por tipo Masajista (diferenciar Médico y Fisioterapeuta)
        for (int i = 0; i < selekzioa.size(); ++i) {
            if (selekzioa.get(i).getClass() == Masajista.class) {    //los tipo Futbolistas
                
                niJugadorNiEntrenador.add((Masajista) selekzioa.get(i));
            }
            
            
        }
        for (int g = 0; g < niJugadorNiEntrenador.size(); ++g) {
                if (niJugadorNiEntrenador.get(g).getTitulacion().equals("Fisioterapeuta")) {    //en caso de ser MÉDICO
                    
                    PlantillaOtros.setText(PlantillaOtros.getText() + "Integrante: " + ++cantidadJugadoresTarjeta + "\n" + 
                        niJugadorNiEntrenador.get(g) + "\n" + "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n");
                
                } else if (niJugadorNiEntrenador.get(g).getTitulacion().equals("Medico")) {
                    
                    PlantillaMedicos.setText(PlantillaMedicos.getText() + "Integrante: " + ++cantidadJugadoresTarjeta + "\n" + 
                        niJugadorNiEntrenador.get(g) + "\n" + "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n");
                    
                }
            }
        
        /*for (int g = 0; g < niJugadorNiEntrenador.size(); ++g) {
                if (niJugadorNiEntrenador.get(g).getTitulacion().equals("Medico")) {    //en caso de ser Fisioterapeuta / de NO SER MÉDICO
                    PlantillaMedicos.setText(PlantillaMedicos.getText() + "Integrante: " + ++cantidadJugadoresTarjeta + "\n" + 
                            niJugadorNiEntrenador.get(g) + "\n" + "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n");
                    //System.out.println(niJugadorNiEntrenador.get(g));
                    
                } else if (niJugadorNiEntrenador.get(g).getTitulacion().equals("Fisioterapeuta")) {
                    ++numFisio;
                    PlantillaOtros.setText(PlantillaOtros.getText() + "Integrante: " + ++cantidadJugadoresTarjeta + "\n" + 
                            niJugadorNiEntrenador.get(g) + "\n" + "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n");
                    //System.out.println(niJugadorNiEntrenador.get(g));
                    System.out.println(numFisio);
                }
            }*/
        
        System.out.println("hola" + niJugadorNiEntrenador);
        
        
    }//GEN-LAST:event_CrearPlantillaActionPerformed

    private void RegistroTarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroTarjetasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RegistroTarjetasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(partidakAntolatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(partidakAntolatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(partidakAntolatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(partidakAntolatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new partidakAntolatu().setVisible(true);
                RandomPlayerAdd.setEnabled(false);  //bloquear el botón "RandomPlayerAdd" según se ejecute el frame
                InfoJugadores.setEnabled(false);
                PlantillaJugadores.setEnabled(false);
                PlantillaEntrenadores.setEnabled(false);
                PlantillaMedicos.setEnabled(false);
                PlantillaOtros.setEnabled(false);
                
                //partidakAntolatu.setPreferredSize(new Dimension(400, 300));
                personalizacionJframe();
            }
        });
        
        //seleccion = EuskalSelekzioa.selekzioa;  //prueba 1
        EuskalSelekzioaMenua.selekzioarenPlantillaOsoaSortu();
        
        EuskalSelekzioaMenua.taldekatuta2(selekzioa);
        //EuskalSelekzioa.selekzioOsoaSortu();
        
        
        
        Partida par1 = new Partida();
    }
    
    /**
     * Método para aplicarle a nuestro jframe unas determinadas 
     * características. 
     */
    public static void personalizacionJframe() {
            //JFrame todasLasTarjetas = new JFrame("Partidak 112");
            //adri.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            
            
            /*adri.setPreferredSize(new Dimension(400, 300));
            adri.pack();
            adri.setLocationRelativeTo(null);
            adri.setVisible(true);*/
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton CrearPlantilla;
    public static javax.swing.JLabel ElegirRandomPonerT;
    public static javax.swing.JLabel FiltroEntrenadores;
    public static javax.swing.JLabel FiltroJugadores;
    public static javax.swing.JLabel FiltroMedicos;
    public static javax.swing.JLabel FiltroOtros;
    public static javax.swing.JTextArea InfoJugadores;
    public static javax.swing.JTextArea PlantillaEntrenadores;
    public static javax.swing.JTextArea PlantillaJugadores;
    public static javax.swing.JTextArea PlantillaMedicos;
    public static javax.swing.JTextArea PlantillaOtros;
    public static javax.swing.JButton RandomPlayerAdd;
    private javax.swing.JButton RegistroTarjetas;
    public static javax.swing.JLabel VerNombresJugadores;
    public static javax.swing.JLabel VerPlantillaNombres;
    public static javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
