/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basicgui;

/**
 *
 * @author arceredillo.adrian
 */
public class Kalku extends javax.swing.JFrame {

    private String[] valores = {"0", "1", "2", "3", "4",
        "5", "6", "7", "8", "9",
        "+", "-", "x", "/", "="
    };

    /**
     * Creates new form Kalku
     */
    public Kalku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBotonY = new javax.swing.JButton();
        jBoton0 = new javax.swing.JButton();
        jBotonComa = new javax.swing.JButton();
        jBoton1 = new javax.swing.JButton();
        jBoton2 = new javax.swing.JButton();
        jBoton3 = new javax.swing.JButton();
        jBoton4 = new javax.swing.JButton();
        jBoton5 = new javax.swing.JButton();
        jBoton6 = new javax.swing.JButton();
        jBoton7 = new javax.swing.JButton();
        jBoton8 = new javax.swing.JButton();
        jBoton9 = new javax.swing.JButton();
        jBotonDiv = new javax.swing.JButton();
        jBotonMulti = new javax.swing.JButton();
        jBotonSuma = new javax.swing.JButton();
        jBotonResta = new javax.swing.JButton();
        jBotonIgual = new javax.swing.JButton();
        jLabelDatoUno = new javax.swing.JLabel();
        jLabelDatoDos = new javax.swing.JLabel();
        jTextoPantalla = new javax.swing.JTextField();
        jPrimerValor = new javax.swing.JLabel();
        jSegundoValor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBotonY.setText("y");
        jBotonY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonYActionPerformed(evt);
            }
        });

        jBoton0.setText("0");
        jBoton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton0ActionPerformed(evt);
            }
        });

        jBotonComa.setText(",");
        jBotonComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonComaActionPerformed(evt);
            }
        });

        jBoton1.setText("1");
        jBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton1ActionPerformed(evt);
            }
        });

        jBoton2.setText("2");
        jBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton2ActionPerformed(evt);
            }
        });

        jBoton3.setText("3");
        jBoton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton3ActionPerformed(evt);
            }
        });

        jBoton4.setText("4");
        jBoton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton4ActionPerformed(evt);
            }
        });

        jBoton5.setText("5");
        jBoton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton5ActionPerformed(evt);
            }
        });

        jBoton6.setText("6");
        jBoton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton6ActionPerformed(evt);
            }
        });

        jBoton7.setText("7");
        jBoton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton7ActionPerformed(evt);
            }
        });

        jBoton8.setText("8");
        jBoton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton8ActionPerformed(evt);
            }
        });

        jBoton9.setText("9");
        jBoton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton9ActionPerformed(evt);
            }
        });

        jBotonDiv.setText("÷");
        jBotonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonDivActionPerformed(evt);
            }
        });

        jBotonMulti.setText("x");
        jBotonMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonMultiActionPerformed(evt);
            }
        });

        jBotonSuma.setText("+");
        jBotonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonSumaActionPerformed(evt);
            }
        });

        jBotonResta.setText("-");
        jBotonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonRestaActionPerformed(evt);
            }
        });

        jBotonIgual.setText("=");
        jBotonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonIgualActionPerformed(evt);
            }
        });

        jLabelDatoUno.setText("Dato 1:");

        jLabelDatoDos.setText("Dato 2:");

        jPrimerValor.setText("...");

        jSegundoValor.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBoton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBoton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBoton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBotonY, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBoton0, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBotonComa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBoton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBoton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBoton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBoton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBoton8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBoton9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBotonDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBotonSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBotonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBotonMulti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBotonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDatoUno)
                            .addComponent(jLabelDatoDos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPrimerValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSegundoValor, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)))
                    .addComponent(jTextoPantalla))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDatoUno)
                    .addComponent(jPrimerValor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDatoDos)
                    .addComponent(jSegundoValor))
                .addGap(18, 18, 18)
                .addComponent(jTextoPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBoton7)
                    .addComponent(jBoton8)
                    .addComponent(jBoton9)
                    .addComponent(jBotonDiv)
                    .addComponent(jBotonMulti))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBoton4)
                    .addComponent(jBoton5)
                    .addComponent(jBoton6)
                    .addComponent(jBotonSuma)
                    .addComponent(jBotonResta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBoton1)
                            .addComponent(jBoton2)
                            .addComponent(jBoton3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBotonY)
                            .addComponent(jBoton0)
                            .addComponent(jBotonComa)))
                    .addComponent(jBotonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBoton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton0ActionPerformed
        // TODO add your handling code here:
        jTextoPantalla.setText(jTextoPantalla.getText() + valores[0]);
    }//GEN-LAST:event_jBoton0ActionPerformed

    private void jBotonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonIgualActionPerformed
        // TODO add your handling code here:

        String valorDos = jTextoPantalla.getText();
        
        String separatorSuma = "+";
        int posSeparatorSuma = jTextoPantalla.getText().indexOf(separatorSuma);
        
        String separatorResta = "-";
        int posSeparatorResta = jTextoPantalla.getText().indexOf(separatorResta);
        
        String separatorMulti = "x";
        int posSeparatorMulti = jTextoPantalla.getText().indexOf(separatorMulti);
        
        String separatorDiv = "/";
        int posSeparatorDiv = jTextoPantalla.getText().indexOf(separatorDiv);
        
        
        int resultadoOperacion = 0;

        /*zenbakitzailea = Integer.valueOf(valorDos.substring(0, posSeparator));
        izendatzailea = Integer.valueOf(valorDos.substring(posSeparator + separator.length()));*/
        if (jBotonSuma.getText() != " " && jBotonResta.getText() == " " && jBotonMulti.getText() == " " && jBotonDiv.getText() == " ") {
            jSegundoValor.setText(valorDos.substring(posSeparatorSuma + separatorSuma.length()));
            resultadoOperacion = (Integer.valueOf(jPrimerValor.getText())) + (Integer.valueOf(jSegundoValor.getText()));
            jTextoPantalla.setText(Integer.toString(resultadoOperacion));
        } else if (jBotonResta.getText() != " " && jBotonSuma.getText() == " " && jBotonMulti.getText() == " " && jBotonDiv.getText() == " ") {
            jSegundoValor.setText(valorDos.substring(posSeparatorResta + separatorResta.length()));
            resultadoOperacion = (Integer.valueOf(jPrimerValor.getText())) - (Integer.valueOf(jSegundoValor.getText()));
            jTextoPantalla.setText(Integer.toString(resultadoOperacion));
        } else if (jBotonMulti.getText() != " " && jBotonSuma.getText() == " " && jBotonResta.getText() == " " && jBotonDiv.getText() == " ") {
            jSegundoValor.setText(valorDos.substring(posSeparatorMulti + separatorMulti.length()));
            resultadoOperacion = (Integer.valueOf(jPrimerValor.getText())) * (Integer.valueOf(jSegundoValor.getText()));
            jTextoPantalla.setText(Integer.toString(resultadoOperacion));
        } else if (jBotonDiv.getText() != " " && jBotonSuma.getText() == " " && jBotonResta.getText() == " " && jBotonMulti.getText() == " ") {
            jSegundoValor.setText(valorDos.substring(posSeparatorDiv + separatorDiv.length()));
            resultadoOperacion = (Integer.valueOf(jPrimerValor.getText()) / (Integer.valueOf(jSegundoValor.getText())));
            jTextoPantalla.setText(Integer.toString(resultadoOperacion));
        }

    }//GEN-LAST:event_jBotonIgualActionPerformed

    private void jBotonComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonComaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBotonComaActionPerformed

    private void jBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton1ActionPerformed
        // TODO add your handling code here:
        jTextoPantalla.setText(jTextoPantalla.getText() + valores[1]);
    }//GEN-LAST:event_jBoton1ActionPerformed

    private void jBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton2ActionPerformed
        // TODO add your handling code here:
        jTextoPantalla.setText(jTextoPantalla.getText() + valores[2]);
    }//GEN-LAST:event_jBoton2ActionPerformed

    private void jBoton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton3ActionPerformed
        // TODO add your handling code here:
        jTextoPantalla.setText(jTextoPantalla.getText() + valores[3]);
    }//GEN-LAST:event_jBoton3ActionPerformed

    private void jBoton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton4ActionPerformed
        // TODO add your handling code here:
        jTextoPantalla.setText(jTextoPantalla.getText() + valores[4]);
    }//GEN-LAST:event_jBoton4ActionPerformed

    private void jBoton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton5ActionPerformed
        // TODO add your handling code here:
        jTextoPantalla.setText(jTextoPantalla.getText() + valores[5]);
    }//GEN-LAST:event_jBoton5ActionPerformed

    private void jBoton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton6ActionPerformed
        // TODO add your handling code here:
        jTextoPantalla.setText(jTextoPantalla.getText() + valores[6]);
    }//GEN-LAST:event_jBoton6ActionPerformed

    private void jBoton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton7ActionPerformed
        // TODO add your handling code here:
        jTextoPantalla.setText(jTextoPantalla.getText() + valores[7]);
    }//GEN-LAST:event_jBoton7ActionPerformed

    private void jBoton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton8ActionPerformed
        // TODO add your handling code here:
        jTextoPantalla.setText(jTextoPantalla.getText() + valores[8]);
    }//GEN-LAST:event_jBoton8ActionPerformed

    private void jBoton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton9ActionPerformed
        // TODO add your handling code here:
        jTextoPantalla.setText(jTextoPantalla.getText() + valores[9]);
    }//GEN-LAST:event_jBoton9ActionPerformed

    private void jBotonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonDivActionPerformed
        // TODO add your handling code here:
        if (jPrimerValor.getText() == "...") {
            jPrimerValor.setText(jTextoPantalla.getText());
            jTextoPantalla.setText(jTextoPantalla.getText() + valores[13]);
            //jTextoPantalla.setText("");

        } else {
            //jSegundoValor.setText(jTextoPantalla.getText());
        }

        jBotonMulti.setText(" ");
        jBotonSuma.setText(" ");
        jBotonResta.setText(" ");

    }//GEN-LAST:event_jBotonDivActionPerformed

    private void jBotonMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonMultiActionPerformed
        // TODO add your handling code here:
        if (jPrimerValor.getText() == "...") {
            jPrimerValor.setText(jTextoPantalla.getText());
            jTextoPantalla.setText(jTextoPantalla.getText() + valores[12]);
            //jTextoPantalla.setText("");

        } else {
            //jSegundoValor.setText(jTextoPantalla.getText());
        }

        jBotonDiv.setText(" ");
        jBotonSuma.setText(" ");
        jBotonResta.setText(" ");

    }//GEN-LAST:event_jBotonMultiActionPerformed

    private void jBotonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonSumaActionPerformed
        // TODO add your handling code here:

        if (jPrimerValor.getText() == "...") {
            jPrimerValor.setText(jTextoPantalla.getText());
            jTextoPantalla.setText(jTextoPantalla.getText() + valores[10]);
            //jTextoPantalla.setText("");

        } else {
            //jSegundoValor.setText(jTextoPantalla.getText());
        }

        jBotonMulti.setText(" ");
        jBotonDiv.setText(" ");
        jBotonResta.setText(" ");
    }//GEN-LAST:event_jBotonSumaActionPerformed

    private void jBotonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonRestaActionPerformed
        // TODO add your handling code here:
        if (jPrimerValor.getText() == "...") {
            jPrimerValor.setText(jTextoPantalla.getText());
            jTextoPantalla.setText(jTextoPantalla.getText() + valores[11]);
            //jTextoPantalla.setText("");

        } else {
            //jSegundoValor.setText(jTextoPantalla.getText());
        }

        jBotonMulti.setText(" ");
        jBotonSuma.setText(" ");
        jBotonDiv.setText(" ");
    }//GEN-LAST:event_jBotonRestaActionPerformed

    private void jBotonYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBotonYActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBoton0;
    private javax.swing.JButton jBoton1;
    private javax.swing.JButton jBoton2;
    private javax.swing.JButton jBoton3;
    private javax.swing.JButton jBoton4;
    private javax.swing.JButton jBoton5;
    private javax.swing.JButton jBoton6;
    private javax.swing.JButton jBoton7;
    private javax.swing.JButton jBoton8;
    private javax.swing.JButton jBoton9;
    private javax.swing.JButton jBotonComa;
    private javax.swing.JButton jBotonDiv;
    private javax.swing.JButton jBotonIgual;
    private javax.swing.JButton jBotonMulti;
    private javax.swing.JButton jBotonResta;
    private javax.swing.JButton jBotonSuma;
    private javax.swing.JButton jBotonY;
    private javax.swing.JLabel jLabelDatoDos;
    private javax.swing.JLabel jLabelDatoUno;
    private javax.swing.JLabel jPrimerValor;
    private javax.swing.JLabel jSegundoValor;
    private javax.swing.JTextField jTextoPantalla;
    // End of variables declaration//GEN-END:variables
}

/*
https://byspel.com/crear-una-calculadora-en-java-con-netbeans-interfaz-grafica/
https://programmerclick.com/article/31641160253/
 */
