/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jolasa;

import com.sun.glass.ui.Size;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Hitza;
//import static model.Hitza.hayGuiones;

/**
 *
 * @author arceredillo.adrian
 */
public class UrkatuaAdrian extends javax.swing.JFrame {

    /**
     * Creates new form UrkatuaJFrame
     */
    public UrkatuaAdrian() {
        this.setTitle("Urkatua Adrian");    //ponerle un titulo a la ventana que se abre (jframe)
        initComponents();
        //jGuionesIniciales.setText(hitza1.getStrAsmatutakoa());
        //jGuionesIniciales.setText("");
    }

    public void paint(Graphics draw) {
        //esto solamente lo utilizaré para darle un nuevo color de fondo al jframe
        getContentPane().setBackground(new Color(70, 80, 70));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        button1 = new java.awt.Button();
        jButtonEgiaztatu = new javax.swing.JButton();
        jCasillaLetra = new javax.swing.JTextField();
        jTextoIndicacion1 = new javax.swing.JLabel();
        jTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtextoCon3Fallos = new javax.swing.JLabel();
        jArrayGuiones = new javax.swing.JLabel();
        jButtonComienzo = new javax.swing.JButton();
        jPalabraGuiones = new javax.swing.JLabel();
        jPalabraOculta = new javax.swing.JLabel();
        jBienMal = new javax.swing.JLabel();
        jGuionesIniciales = new javax.swing.JLabel();
        jDibujo = new javax.swing.JLabel();
        jTrampa = new javax.swing.JButton();
        jSolucion = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLetrasMal = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTodoNada = new javax.swing.JButton();
        jVerTrampa = new javax.swing.JLabel();
        jSalir = new javax.swing.JButton();
        jPartidaNueva = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        button1.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonEgiaztatu.setText("Egiaztatu");
        jButtonEgiaztatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEgiaztatuActionPerformed(evt);
            }
        });

        jCasillaLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCasillaLetraActionPerformed(evt);
            }
        });

        jTextoIndicacion1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTextoIndicacion1.setForeground(new java.awt.Color(255, 255, 255));
        jTextoIndicacion1.setText("Aukeratu hizkia:");

        jTitulo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jTitulo.setForeground(new java.awt.Color(153, 255, 153));
        jTitulo.setText("URKATUAREN JOLASA");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hitz ezkutuak ez daukan hizkiak:");

        jtextoCon3Fallos.setBackground(new java.awt.Color(255, 255, 255));
        jtextoCon3Fallos.setForeground(new java.awt.Color(255, 255, 255));

        jArrayGuiones.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jArrayGuiones.setForeground(new java.awt.Color(153, 255, 153));
        jArrayGuiones.setText("ONGI ETORRI !!");

        jButtonComienzo.setText("Hasiera");
        jButtonComienzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComienzoActionPerformed(evt);
            }
        });

        jPalabraOculta.setForeground(new java.awt.Color(153, 255, 153));
        jPalabraOculta.setText("...");

        jBienMal.setBackground(new java.awt.Color(255, 255, 255));
        jBienMal.setForeground(new java.awt.Color(255, 255, 255));
        jBienMal.setText("Sakatu \"Hasiera\" jolasteko.");

        jGuionesIniciales.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N

        jDibujo.setBackground(new java.awt.Color(204, 255, 255));

        jTrampa.setText("Tranpa Egin");
        jTrampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTrampaActionPerformed(evt);
            }
        });

        jSolucion.setForeground(new java.awt.Color(255, 255, 255));
        jSolucion.setText("Hitza:");

        jLetrasMal.setBackground(new java.awt.Color(255, 255, 255));
        jLetrasMal.setForeground(new java.awt.Color(255, 255, 255));
        jLetrasMal.setText("Akatsak:");

        jTodoNada.setText("Todo/Nada");
        jTodoNada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTodoNadaActionPerformed(evt);
            }
        });

        jVerTrampa.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jVerTrampa.setForeground(new java.awt.Color(255, 255, 153));

        jSalir.setText("Irten");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });

        jPartidaNueva.setText("Partida Berria");
        jPartidaNueva.setToolTipText("");
        jPartidaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPartidaNuevaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 55, Short.MAX_VALUE)
                .addComponent(jPalabraGuiones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jTextoIndicacion1)
                            .addGap(18, 18, 18)
                            .addComponent(jCasillaLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonEgiaztatu))
                        .addComponent(jArrayGuiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBienMal, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jLetrasMal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonComienzo)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jSolucion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPalabraOculta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTodoNada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSalir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jVerTrampa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTrampa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jtextoCon3Fallos, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jGuionesIniciales, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(20, 20, 20)))
                    .addComponent(jPartidaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPalabraGuiones)
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTitulo)
                                .addComponent(jPalabraOculta))
                            .addComponent(jSolucion, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTrampa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonEgiaztatu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCasillaLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextoIndicacion1)
                                .addComponent(jButtonComienzo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLetrasMal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPartidaNueva)
                                .addGap(4, 4, 4)
                                .addComponent(jVerTrampa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtextoCon3Fallos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBienMal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTodoNada, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jArrayGuiones, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jGuionesIniciales)
                            .addComponent(jSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEgiaztatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEgiaztatuActionPerformed
        // TODO add your handling code here:
        //int numeroIntentos = 3;
        int miContadorErrores = 0;

        jVerTrampa.setText("");
        if (jCasillaLetra.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Dirudi ez duzula hizkirik sartu. \nMesedez, sartu letra bat. ", "Errorea", JOptionPane.WARNING_MESSAGE);
        }

        //for (int i = 0; i < hitza1.getHitza().length(); ++i) {
        if (hitza1.egiaztatu(jCasillaLetra.getText().toLowerCase().charAt(0))) {
            jBienMal.setForeground(new Color(102, 204, 255));
            jBienMal.setText("Bien!! Ya te queda menos! ");

            hitza1.egiaztatu(jCasillaLetra.getText().charAt(0));

            jArrayGuiones.setText(hitza1.getStrAsmatutakoa());
            jCasillaLetra.setText("");

            boolean juegoTerminado = true;
            for (int i = 0; i < hitza1.getAsmatutakoa().length; ++i) {
                if ((hitza1.getAsmatutakoa()[i] == '-')) {
                    juegoTerminado = false;
                }
            }
            if (juegoTerminado == true) {
                JOptionPane.showMessageDialog(null, "¡Primeran!. \nUrkatuaren jolasa bukatu duzu! ", "ZORIONAK!", JOptionPane.WARNING_MESSAGE);
                jBienMal.setText("Oso ondo!! Hitza aurkitu duzu. ");
                //if (jBienMal.getText().equals("Oso ondo!! Hitza aurkitu duzu. ")) {}
                jDibujo.setIcon(new ImageIcon(ClassLoader.getSystemResource("irudiak/irudiaFinal.png")));
                jPalabraOculta.setText(new String(hitza1.getHitza()));
                jCasillaLetra.setEnabled(false);
                jTodoNada.setEnabled(false);
                jButtonEgiaztatu.setEnabled(false);
                jButtonComienzo.setEnabled(false);
                jTrampa.setEnabled(false);
            }
            jCasillaLetra.setText("");

        } else {
            //--numeroIntentos;
            miContadorErrores = jtextoCon3Fallos.getText().length();    //para contar los fallos, he calculado la longitud del label (teniendo en cuenta las comas)
            hitza1.setErabilitakoAldiak(hitza1.getErabilitakoAldiak() + 1);

            jtextoCon3Fallos.setForeground(new Color(255, 102, 102));
            jtextoCon3Fallos.setText(jtextoCon3Fallos.getText() + jCasillaLetra.getText() + ", ");
            jBienMal.setForeground(new Color(255, 102, 102));
            jBienMal.setText("Txarto!! La letra no ha sido encontrada... ");

            if (miContadorErrores == 0) {
                jDibujo.setIcon(new ImageIcon(ClassLoader.getSystemResource("irudiak/irudia1.png")));
                //System.out.println(ClassLoader.getSystemResource("irudiak/irudia1.png"));
            } else if (miContadorErrores == 3) {
                jDibujo.setIcon(new ImageIcon(ClassLoader.getSystemResource("irudiak/irudia2.png")));
            } else if (miContadorErrores == 6) {
                jDibujo.setIcon(new ImageIcon(ClassLoader.getSystemResource("irudiak/irudia3.png")));
            } else if (miContadorErrores == 9) {
                jDibujo.setIcon(new ImageIcon(ClassLoader.getSystemResource("irudiak/irudia4.png")));
            } else if (miContadorErrores == 12) {
                jDibujo.setIcon(new ImageIcon(ClassLoader.getSystemResource("irudiak/irudia5.png")));
            } else if (miContadorErrores == 15) {
                jDibujo.setIcon(new ImageIcon(ClassLoader.getSystemResource("irudiak/irudia6.png")));
                JOptionPane.showMessageDialog(null, "Te has quedado sin intentos. Cierra el programa \ny vuelve a intentarlo. Buena suerte! \n\nLa palabra era: " + hitza1.getHitza() + ". ", "Errorea", JOptionPane.WARNING_MESSAGE);
                jBienMal.setText("FIN. Te has quedado sin intentos... ");
                jPalabraOculta.setForeground(new Color(255, 102, 102));
                jPalabraOculta.setText(new String(hitza1.getHitza()));
                jButtonEgiaztatu.setEnabled(false);
                jTodoNada.setEnabled(false);
                jCasillaLetra.setEnabled(false);
                jButtonComienzo.setEnabled(false);
                jTrampa.setEnabled(false);
            }
            jCasillaLetra.setText("");

        }

        try {
            //char casillaVacia = jCasillaLetra.getText().charAt(2);
            //System.out.println(casillaVacia);
            /*if (jCasillaLetra.getText().equals("")) {
                System.out.println(jArrayGuiones.getText().charAt(2));
            }*/
            //System.out.println(jCasillaLetra.getText().charAt(0));
        } catch (StringIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Dirudi ez duzula hizkirik sartu. \nMesedez, sartu letra bat. ", "Errorea", JOptionPane.WARNING_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Dirudi ez duzula hizkirik sartu. \nMesedez, sartu letra bat. ", "Errorea", JOptionPane.WARNING_MESSAGE);
            System.out.println("Tienes que meter una letra. ");
        }


    }//GEN-LAST:event_jButtonEgiaztatuActionPerformed

    private void jButtonComienzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComienzoActionPerformed
        // TODO add your handling code here:
        jArrayGuiones.setText(new String(hitza1.getStrAsmatutakoa()));
        //jPalabraGuiones.setText(new String(hitza1.getHitza()));
        //jPalabraOculta.setText(new String(hitza1.getHitza()));


    }//GEN-LAST:event_jButtonComienzoActionPerformed

    private void jTrampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTrampaActionPerformed
        // TODO add your handling code here:
        jVerTrampa.setText("Hitza: " + new String(hitza1.getHitza()));
    }//GEN-LAST:event_jTrampaActionPerformed

    private void jCasillaLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCasillaLetraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCasillaLetraActionPerformed

    private void jTodoNadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTodoNadaActionPerformed
        // TODO add your handling code here:

        jVerTrampa.setText("");

        if (jtextoCon3Fallos.getText().length() != 0) {
            JOptionPane.showMessageDialog(null, "Zentitzen da!\nBehin modu nagusian akatsen bat egin ondoren, ezin da joko modu hau erabili.\nItxi programa eta saiatu berriro. ", "Errorea", JOptionPane.WARNING_MESSAGE);
            jTodoNada.setEnabled(false);
            //System.out.println("no");
        } else {
            String siSePuede = JOptionPane.showInputDialog("Ausarta zara!\nJoko modu honetan aukera bakarra daukazu. Zein da zure\nustez ezkutuko hitza? ");
            System.out.println(siSePuede);
            if (hitza1.getHitza().equals(siSePuede)) {

                JOptionPane.showMessageDialog(null, "¡Primeran!. \nUrkatuaren jolasa bukatu duzu! ", "Hurrengoan agian...!", JOptionPane.WARNING_MESSAGE);

                jPalabraOculta.setForeground(new Color(153, 255, 153));
                jPalabraOculta.setText(hitza1.getHitza());
                jBienMal.setForeground(new Color(102, 204, 255));
                jBienMal.setText("Primeran!! Asmatu duzu. ");
                jDibujo.setIcon(new ImageIcon(ClassLoader.getSystemResource("irudiak/irudiaFinal.png")));
                jCasillaLetra.setEnabled(false);
                jButtonEgiaztatu.setEnabled(false);
                jTodoNada.setEnabled(false);
                jButtonComienzo.setEnabled(false);
                jTrampa.setEnabled(false);

                //UrkatuaAdrian.dispatchEvent(new WindowEvent(UrkatuaAdrian, WindowEvent.WINDOW_CLOSING));
            } else {
                JOptionPane.showMessageDialog(null, "Txarto!!. \nSarturiko datua ez da zuzena. Ezkutuko hitza honako \nhau da: \n\nHitza: " + hitza1.getHitza(), "Gertu baina...Ez!", JOptionPane.WARNING_MESSAGE);
                jPalabraOculta.setForeground(new Color(255, 102, 102));
                jPalabraOculta.setText(hitza1.getHitza());
                jBienMal.setForeground(new Color(255, 102, 102));
                jBienMal.setText("FIN. Te has quedado sin intentos... ");
                jCasillaLetra.setEnabled(false);
                jButtonEgiaztatu.setEnabled(false);
                jTodoNada.setEnabled(false);
                jButtonComienzo.setEnabled(false);
                jTrampa.setEnabled(false);
            }
            //System.out.println("si");
            //setDefaultCloseOperation(UrkatuaAdrian.EXIT_ON_CLOSE);
        }

        /*String oneChance = JOptionPane.showInputDialog("Ausarta zara!\nJoko modu honetan aukera bakarra daukazu. Zein da zure\nustez ezkutuko hitza? ");
        String entradaTodoNada = oneChance;
        
        if (entradaTodoNada.equals(hitza1.getHitza())) {
            System.out.println("Has ganado!!! ");
        }*/
    }//GEN-LAST:event_jTodoNadaActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        // TODO add your handling code here:
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        
    }//GEN-LAST:event_jSalirActionPerformed

    private void jPartidaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPartidaNuevaActionPerformed
        // TODO add your handling code here:
        
        this.dispose();     //cerrar la ventana del jframe y abrir una nueva ventana
        
        
        hitza1.setHitza("");
        hitza1.hitzBatAukeratu();
        System.out.println(hitza1.getHitza());
        hitza1.setAsmatutakoa(hitza1.getAsmatutakoa());
        jArrayGuiones.setText(hitza1.getStrAsmatutakoa());
        jtextoCon3Fallos.setText("");
        jCasillaLetra.setText("");
        jBienMal.setText("");
        jVerTrampa.setText("Hitza: " + new String(hitza1.getHitza()));
        jDibujo.setIcon(new ImageIcon(ClassLoader.getSystemResource("")));
        
        jCasillaLetra.setEnabled(true);
        jTodoNada.setEnabled(true);
        jButtonEgiaztatu.setEnabled(true);
        jButtonComienzo.setEnabled(true);
        jTrampa.setEnabled(true);

        new UrkatuaAdrian().setVisible(true);
    }//GEN-LAST:event_jPartidaNuevaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UrkatuaAdrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UrkatuaAdrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UrkatuaAdrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UrkatuaAdrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UrkatuaAdrian().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    public static javax.swing.JLabel jArrayGuiones;
    public static javax.swing.JLabel jBienMal;
    public static javax.swing.JButton jButtonComienzo;
    public static javax.swing.JButton jButtonEgiaztatu;
    public static javax.swing.JTextField jCasillaLetra;
    private javax.swing.JLabel jDibujo;
    public static javax.swing.JLabel jGuionesIniciales;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLetrasMal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    public static javax.swing.JLabel jPalabraGuiones;
    public static javax.swing.JLabel jPalabraOculta;
    private javax.swing.JButton jPartidaNueva;
    private javax.swing.JButton jSalir;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jSolucion;
    private javax.swing.JLabel jTextoIndicacion1;
    private javax.swing.JLabel jTitulo;
    public static javax.swing.JButton jTodoNada;
    private javax.swing.JButton jTrampa;
    private javax.swing.JLabel jVerTrampa;
    public static javax.swing.JLabel jtextoCon3Fallos;
    // End of variables declaration//GEN-END:variables

    private Hitza hitza1 = new Hitza();

}


/*
https://www.tutorialspoint.com/how-to-create-a-jlabel-with-an-image-icon-in-java
http://www.herongyang.com/JVM/ClassLoader-getSystemResource-Method-Find-File.html
https://javadesde0.com/cuadros-de-dialogo-con-joptionpane-de-swing/ 
https://mkyong.com/swing/java-swing-joptionpane-showinputdialog-example/ -> input mensaje
https://alvinalexander.com/java/jframe-title-set/
 */
