/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frameak;

import java.awt.Color;
import java.awt.Graphics;
import model.Kutxa;
import model.Laukizuzena;
import model.Puntua;

/**
 *
 * @author arceredillo.adrian
 */
public class JFrameMarrazkiak extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMarrazkiak
     */
    public JFrameMarrazkiak() {
        initComponents();
        this.setResizable(false);
        JComboBoxFiguras.addItem("Puntua");
        JComboBoxFiguras.addItem("Laukizuzena");
        JComboBoxFiguras.addItem("Kutxa");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTextFieldAltuera = new javax.swing.JTextField();
        JLabelAltuera = new javax.swing.JLabel();
        JLabelLuzera = new javax.swing.JLabel();
        JLabelZabalera = new javax.swing.JLabel();
        JComboBoxFiguras = new javax.swing.JComboBox<>();
        JLabelElegirIrudia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        JTextFieldAltuera.setText("Altuera");

        JLabelAltuera.setText("Altuera");

        JLabelLuzera.setText("Luzera");

        JLabelZabalera.setText("Zabalera");

        JComboBoxFiguras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxFigurasActionPerformed(evt);
            }
        });

        JLabelElegirIrudia.setText("Elegir figura: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(472, Short.MAX_VALUE)
                .addComponent(JLabelElegirIrudia)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JComboBoxFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelZabalera)
                    .addComponent(JLabelAltuera)
                    .addComponent(JTextFieldAltuera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelLuzera))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(JLabelLuzera)
                .addGap(40, 40, 40)
                .addComponent(JLabelZabalera)
                .addGap(82, 82, 82)
                .addComponent(JLabelAltuera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTextFieldAltuera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JComboBoxFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelElegirIrudia))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
        int coordX = evt.getX();
        int coordY = evt.getY();
        //int altura = Integer.parseInt(JTextFieldAltuera.getText());
        //Kutxa k1 = new Kutxa(new Puntua(coordX, coordY),new Puntua(coordX + 100, coordY - 40), altura);
        
        Laukizuzena rec1 = new Laukizuzena(new Puntua(coordX, coordY),new Puntua(coordX + 100,coordY - 40));
        Puntua p1 = new Puntua(coordX, coordY);
        
        Graphics g = this.getGraphics();
        //k1.marraztu(g);
        //rec1.marraztu(g);
        //p1.marraztu(g);
        
        
        if (JComboBoxFiguras.getSelectedIndex() == 0) {
            p1.marraztu(g);
        } else if (JComboBoxFiguras.getSelectedIndex() == 1) {
            rec1.marraztu(g);
        } else if (JComboBoxFiguras.getSelectedIndex() == 2) {
            
            
            int altura = Integer.parseInt(JTextFieldAltuera.getText());
            Kutxa k1 = new Kutxa(new Puntua(coordX, coordY),new Puntua(coordX + 100, coordY - 40), altura);
            k1.marraztu(g);
        }
        
        
    }//GEN-LAST:event_formMouseClicked

    private void JComboBoxFigurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxFigurasActionPerformed
        // TODO add your handling code here:
        if (JComboBoxFiguras.getSelectedIndex() == 2) {
            JTextFieldAltuera.setEditable(true);
            JTextFieldAltuera.setEnabled(true);
            JTextFieldAltuera.setText("");
        }
        
    }//GEN-LAST:event_JComboBoxFigurasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMarrazkiak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMarrazkiak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMarrazkiak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMarrazkiak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMarrazkiak().setVisible(true);
                JTextFieldAltuera.setText("Sartu balio bat: ");
                JTextFieldAltuera.setEditable(false);
                JTextFieldAltuera.setEnabled(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> JComboBoxFiguras;
    public static javax.swing.JLabel JLabelAltuera;
    public static javax.swing.JLabel JLabelElegirIrudia;
    public static javax.swing.JLabel JLabelLuzera;
    public static javax.swing.JLabel JLabelZabalera;
    public static javax.swing.JTextField JTextFieldAltuera;
    // End of variables declaration//GEN-END:variables
}
