
package exekutagarriak;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.*;
import model.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author arceredillo.adrian
 */
public class Puntu9Lerro4 extends javax.swing.JFrame {

    /**
     * Creates new form MarrazkiaFrame
     */
    public Puntu9Lerro4() {
        initComponents();
        Graphics g = this.getGraphics();
        g.drawLine(300 / 2, 0, this.getWidth() / 2, this.getHeight());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    //VARIABLE PARA ALMACENAR PUNTOS
    ArrayList<MyPoint> lista = new ArrayList<MyPoint>();
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        
        
        Graphics g = this.getGraphics();
        //DIBUJAR PUNTO
        g.drawRect(evt.getX(), evt.getY(), 5, 5);
        //****DIBUJAR LINEA

        //GUARDAR PUNTOS
        lista.add(new MyPoint(evt.getX(), evt.getY()));
        //DIBUJAR CIRCULOS
        //g.drawOval(100+300, 300-50, 2*50, 2*50);
        //g.drawOval(100+600, 300-50, 2*50, 2*50);
        g.setColor(Color.BLACK);
        
        //PRIMERA fila de circulos
        g.setColor(Color.BLACK);
        g.drawOval(this.getWidth() / 2 - 300, 300+165, 2*50, 2*50);
        g.drawOval(this.getWidth() / 2 - 50, 300+165, 2*50, 2*50);
        g.drawOval(this.getWidth() / 2 + 200, 300+165, 2*50, 2*50);
        
        
        //SEGUNDA fila de circulos
        g.setColor(Color.red);
        g.drawOval(this.getWidth() / 2 - 300, 300-50, 2*50, 2*50);
        g.drawOval(this.getWidth() / 2 - 50, 300-50, 2*50, 2*50);
        g.drawOval(this.getWidth() / 2 + 200, 300-50, 2*50, 2*50);
        
        
        //TERCERA fila de circulos
        g.setColor(Color.BLUE);
        g.drawOval(this.getWidth() / 2 - 300, this.getHeight() / 2 + 150, 2*50, 2*50);
        g.drawOval(this.getWidth() / 2 - 50, this.getHeight() / 2 + 150, 2*50, 2*50);
        g.drawOval(this.getWidth() / 2 + 200, this.getHeight() / 2 + 150, 2*50, 2*50);
        
        
        g.setColor(Color.BLACK);
        g.drawLine(this.getWidth() / 2, 0, this.getWidth() / 2, this.getHeight());
        g.drawLine(0, this.getHeight() / 2, this.getWidth(), this.getHeight() / 2);
        
        
        //OBTENER PUNTOS
        if (lista.size() > 1) {
            //DIBUJAR LÍNEA entr PUNTOS
            g.drawLine(
                    lista.get(lista.size() - 1).getX(),
                    lista.get(lista.size() - 1).getY(),
                    lista.get(lista.size() - 2).getX(),
                    lista.get(lista.size() - 2).getY()
            );
            

        }
        

    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Puntu9Lerro4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Puntu9Lerro4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Puntu9Lerro4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Puntu9Lerro4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Puntu9Lerro4().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
