/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frameak;

import model.Zatikia;

/**
 *
 * @author AdriAlex
 */
public class JFrameBatuBider extends javax.swing.JFrame {

    Zatikia zat1 = new Zatikia();
    Zatikia zat2 = new Zatikia();
    
    
    /**
     * Creates new form JFrameBatuBider
     */
    public JFrameBatuBider() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zat1Zenbakitzailea = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        zat1Izendatzailea = new javax.swing.JTextField();
        jButtonBatuketaBider = new javax.swing.JButton();
        emaitzaZenbakitzailea = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        zat2Izendatzailea = new javax.swing.JTextField();
        zat2Zenbakitzailea = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        emaitzaIzendatzailea = new javax.swing.JTextField();
        jButtonMezua = new javax.swing.JButton();
        JButtonHasiera = new javax.swing.JButton();
        JLabelIzenburua = new javax.swing.JLabel();
        jExplicacionHasi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        zat1Zenbakitzailea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        zat1Zenbakitzailea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zat1ZenbakitzaileaActionPerformed(evt);
            }
        });

        jButtonBatuketaBider.setText("x");
        jButtonBatuketaBider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatuketaBiderActionPerformed(evt);
            }
        });

        emaitzaZenbakitzailea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emaitzaZenbakitzaileaActionPerformed(evt);
            }
        });

        zat2Zenbakitzailea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zat2ZenbakitzaileaActionPerformed(evt);
            }
        });

        jButtonMezua.setText("=");
        jButtonMezua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMezuaActionPerformed(evt);
            }
        });

        JButtonHasiera.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        JButtonHasiera.setText("Random Values");
        JButtonHasiera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonHasieraActionPerformed(evt);
            }
        });

        JLabelIzenburua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JLabelIzenburua.setText("Zatikien arteko batuketa eta biderketak:");

        jExplicacionHasi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jExplicacionHasi.setText("Botoia sakatuz gero, ausazko bi zatiki sortuko dira.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLabelIzenburua)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(zat1Zenbakitzailea)
                                    .addComponent(jSeparator1)
                                    .addComponent(zat1Izendatzailea, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(zat2Zenbakitzailea, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(98, 98, 98)
                                            .addComponent(zat2Izendatzailea, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addComponent(jButtonBatuketaBider)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonMezua, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emaitzaIzendatzailea, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emaitzaZenbakitzailea, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JButtonHasiera)
                        .addGap(18, 18, 18)
                        .addComponent(jExplicacionHasi, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonHasiera, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jExplicacionHasi))
                .addGap(36, 36, 36)
                .addComponent(JLabelIzenburua)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(zat1Zenbakitzailea, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonBatuketaBider)
                                .addComponent(jButtonMezua)))
                        .addGap(18, 18, 18)
                        .addComponent(zat1Izendatzailea, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zat2Zenbakitzailea, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emaitzaZenbakitzailea, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emaitzaIzendatzailea, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(zat2Izendatzailea))))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBatuketaBiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatuketaBiderActionPerformed

        jButtonBatuketaBider.setText("+");
        

    }//GEN-LAST:event_jButtonBatuketaBiderActionPerformed

    private void jButtonMezuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMezuaActionPerformed

        if (jButtonBatuketaBider.getText() == "+") {
            zat1.setZenbakitzailea(Integer.valueOf(zat1Zenbakitzailea.getText()));
            zat1.setIzendatzailea(Integer.valueOf(zat1Izendatzailea.getText()));
            
            zat2.setZenbakitzailea(Integer.valueOf(zat2Zenbakitzailea.getText()));
            zat2.setIzendatzailea(Integer.valueOf(zat2Izendatzailea.getText()));
            
            Zatikia zat3 = Zatikia.batu(zat1, zat2);
            emaitzaZenbakitzailea.setText(Integer.toString(zat3.getZenbakitzailea()));
            emaitzaIzendatzailea.setText(Integer.toString(zat3.getIzendatzailea()));
            
        } else if (jButtonBatuketaBider.getText() == "x") {
            zat1.setZenbakitzailea(Integer.valueOf(zat1Zenbakitzailea.getText()));
            zat1.setIzendatzailea(Integer.valueOf(zat1Izendatzailea.getText()));
            
            zat2.setZenbakitzailea(Integer.valueOf(zat2Zenbakitzailea.getText()));
            zat2.setIzendatzailea(Integer.valueOf(zat2Izendatzailea.getText()));
            
            Zatikia zat3 = Zatikia.biderkatu(zat1, zat2);
            emaitzaZenbakitzailea.setText(Integer.toString(zat3.getZenbakitzailea()));
            emaitzaIzendatzailea.setText(Integer.toString(zat3.getIzendatzailea()));
        }

    }//GEN-LAST:event_jButtonMezuaActionPerformed

    private void zat1ZenbakitzaileaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zat1ZenbakitzaileaActionPerformed

        zat1Zenbakitzailea.setText(Integer.toString(zat1.getZenbakitzailea()));

    }//GEN-LAST:event_zat1ZenbakitzaileaActionPerformed

    private void emaitzaZenbakitzaileaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emaitzaZenbakitzaileaActionPerformed

        
        
    }//GEN-LAST:event_emaitzaZenbakitzaileaActionPerformed

    private void zat2ZenbakitzaileaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zat2ZenbakitzaileaActionPerformed

        zat2Zenbakitzailea.setText(Integer.toString(zat2.getZenbakitzailea()));

    }//GEN-LAST:event_zat2ZenbakitzaileaActionPerformed

    private void JButtonHasieraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonHasieraActionPerformed

        zat1Zenbakitzailea.setText(Integer.toString(zat1.getZenbakitzailea()));
        zat1Izendatzailea.setText(Integer.toString(zat1.getIzendatzailea()));

        zat2Zenbakitzailea.setText(Integer.toString(zat2.getZenbakitzailea()));
        zat2Izendatzailea.setText(Integer.toString(zat2.getIzendatzailea()));

    }//GEN-LAST:event_JButtonHasieraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameBatuBider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameBatuBider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameBatuBider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameBatuBider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameBatuBider().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonHasiera;
    private javax.swing.JLabel JLabelIzenburua;
    private javax.swing.JTextField emaitzaIzendatzailea;
    private javax.swing.JTextField emaitzaZenbakitzailea;
    private javax.swing.JButton jButtonBatuketaBider;
    private javax.swing.JButton jButtonMezua;
    private javax.swing.JLabel jExplicacionHasi;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField zat1Izendatzailea;
    private javax.swing.JTextField zat1Zenbakitzailea;
    private javax.swing.JTextField zat2Izendatzailea;
    private javax.swing.JTextField zat2Zenbakitzailea;
    // End of variables declaration//GEN-END:variables
}


//https://www.daniweb.com/programming/software-development/threads/374126/how-to-link-a-jframe-form-to-a-class-using-netbeans
