/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frameak;

import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import model.Zatikia;

/**
 *
 * @author arceredillo.adrian
 */
public class JFrameAsmatuta extends javax.swing.JFrame {

    Zatikia zatBakoitia = new Zatikia();
    Zatikia zatBikoitia = new Zatikia();

    /**
     * Creates new form JFrameAsmatuta
     */
    public JFrameAsmatuta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBaZenbakitzailea = new javax.swing.JTextField();
        jBaIzendatzailea = new javax.swing.JTextField();
        jBiZenbakitzailea = new javax.swing.JTextField();
        jBiIzendatzailea = new javax.swing.JTextField();
        jBakoitiak = new javax.swing.JLabel();
        jBikoitiak = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jComprobarBakoiti = new javax.swing.JButton();
        jComprobarBikoiti = new javax.swing.JButton();
        jBaCheckedIzenda = new javax.swing.JLabel();
        jBiChecked = new javax.swing.JLabel();
        jBaCheckedZenba = new javax.swing.JLabel();
        jMensajeComprobacionBa = new javax.swing.JLabel();
        jMensajeComprobacionBi = new javax.swing.JLabel();
        jBiCheckedIzenda = new javax.swing.JLabel();
        jBiCheckedZenba = new javax.swing.JLabel();
        jEragiketaMulti = new javax.swing.JButton();
        jEragiketaSuma = new javax.swing.JButton();
        jEragiketaResta = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jEragiketaIzenburua = new javax.swing.JLabel();
        jBaZatikiEragiketak = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jEmaitza = new javax.swing.JButton();
        jEmaitzaZenba = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jEmaitzaIzenda = new javax.swing.JTextField();
        jErrorEmaitza = new javax.swing.JLabel();
        jIrJuego = new javax.swing.JButton();
        jBaHarmartarBalioa = new javax.swing.JLabel();
        jBiHarmartarBalioa = new javax.swing.JLabel();
        jBalioakEzabatu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBaZenbakitzailea.setToolTipText("");
        jBaZenbakitzailea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaZenbakitzaileaActionPerformed(evt);
            }
        });

        jBaIzendatzailea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaIzendatzaileaActionPerformed(evt);
            }
        });

        jBiZenbakitzailea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBiZenbakitzaileaActionPerformed(evt);
            }
        });

        jBiIzendatzailea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBiIzendatzaileaActionPerformed(evt);
            }
        });

        jBakoitiak.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBakoitiak.setText("Zatiki Bakoitia:");

        jBikoitiak.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBikoitiak.setText("Zatiki Bikoitia:");

        jComprobarBakoiti.setText("Zuzena da?");
        jComprobarBakoiti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComprobarBakoitiActionPerformed(evt);
            }
        });

        jComprobarBikoiti.setText("Zuzena da?");
        jComprobarBikoiti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComprobarBikoitiActionPerformed(evt);
            }
        });

        jBaCheckedIzenda.setText("         ");

        jBiChecked.setText("    ");

        jBaCheckedZenba.setText("         ");

        jMensajeComprobacionBa.setText(" ");

        jMensajeComprobacionBi.setText(" ");

        jBiCheckedIzenda.setText("         ");

        jBiCheckedZenba.setText(" ");

        jEragiketaMulti.setText("X");
        jEragiketaMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEragiketaMultiActionPerformed(evt);
            }
        });

        jEragiketaSuma.setText("+");
        jEragiketaSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEragiketaSumaActionPerformed(evt);
            }
        });

        jEragiketaResta.setText("-");
        jEragiketaResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEragiketaRestaActionPerformed(evt);
            }
        });

        jEragiketaIzenburua.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jEragiketaIzenburua.setText("ERAGIKETAK");

        jBaZatikiEragiketak.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBaZatikiEragiketak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBaZatikiEragiketak.setText("Z. Bakoitia");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Z. Bikoitia");

        jEmaitza.setText("=");
        jEmaitza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmaitzaActionPerformed(evt);
            }
        });

        jEmaitzaZenba.setText("   ");
        jEmaitzaZenba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmaitzaZenbaActionPerformed(evt);
            }
        });

        jEmaitzaIzenda.setText("   ");
        jEmaitzaIzenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmaitzaIzendaActionPerformed(evt);
            }
        });

        jErrorEmaitza.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jErrorEmaitza.setText("  ");

        jIrJuego.setText("Jolasa");
        jIrJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIrJuegoActionPerformed(evt);
            }
        });

        jBaHarmartarBalioa.setText(" ");

        jBiHarmartarBalioa.setText(" ");

        jBalioakEzabatu.setText("Balioak Ezabatu");
        jBalioakEzabatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalioakEzabatuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComprobarBakoiti, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jBakoitiak))
                            .addComponent(jComprobarBikoiti, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jBaZatikiEragiketak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jBikoitiak)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBaZenbakitzailea)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(jBiIzendatzailea, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBiZenbakitzailea, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBaIzendatzailea, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBaCheckedIzenda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBiCheckedIzenda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jMensajeComprobacionBa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jMensajeComprobacionBi, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBiChecked, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBaCheckedZenba, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBaHarmartarBalioa, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBiCheckedZenba, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBiHarmartarBalioa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(115, 115, 115)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jErrorEmaitza, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jBalioakEzabatu)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jIrJuego)))))
                                .addGap(40, 40, 40))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jEragiketaSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jEragiketaMulti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jEragiketaResta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(jEmaitza)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jEmaitzaZenba)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jEmaitzaIzenda, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jEragiketaIzenburua)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBaZenbakitzailea, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBaCheckedZenba)
                    .addComponent(jBaHarmartarBalioa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBakoitiak)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComprobarBakoiti)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBaIzendatzailea, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBaCheckedIzenda)
                        .addComponent(jMensajeComprobacionBa)))
                .addGap(16, 16, 16)
                .addComponent(jErrorEmaitza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBiZenbakitzailea, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBiCheckedZenba)
                    .addComponent(jIrJuego)
                    .addComponent(jBiHarmartarBalioa)
                    .addComponent(jBalioakEzabatu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBikoitiak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBiIzendatzailea, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBiChecked)
                    .addComponent(jComprobarBikoiti)
                    .addComponent(jBiCheckedIzenda)
                    .addComponent(jMensajeComprobacionBi))
                .addGap(46, 46, 46)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jEragiketaIzenburua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEragiketaSuma)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEragiketaMulti)
                            .addComponent(jBaZatikiEragiketak)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEragiketaResta))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jEmaitzaZenba, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jEmaitza)
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jEmaitzaIzenda)))))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComprobarBakoitiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComprobarBakoitiActionPerformed
        
        //se mostrará un mensaje emergente si el usuario no ha rellenado/definido alguno de los componentes de la fracción de números IMPARES
        if (jBaZenbakitzailea.getText().equals("") || jBaIzendatzailea.getText().equals("")) {JOptionPane.showMessageDialog(null,"Dirudienez, zenbaki bakoitien zatiki hau ez dago guztiz sortuta. \nBete itzazu eskatzen diren zatikiaren osagai guztiak.", "Errorea",JOptionPane.WARNING_MESSAGE);}
        
        
        //comprobar si la función 1 (IMPARES) está formada por números IMPARES
        if (Integer.valueOf(jBaZenbakitzailea.getText()) % 2 != 0) {
            jBaCheckedZenba.setText("✔");    
        } else {
            jBaCheckedZenba.setText("✖");
        } 

        if (Integer.valueOf(jBaIzendatzailea.getText()) % 2 != 0) {
            jBaCheckedIzenda.setText("✔");
        } else {
            jBaCheckedIzenda.setText("✖");
        }

        if (jBaCheckedZenba.getText() == "✔" && jBaCheckedIzenda.getText() == "✔") {
            
            jMensajeComprobacionBa.setText("Ondo!! Zatiki honek balio egokiak ditu.");
            
            zatBakoitia.setZenbakitzailea(Integer.valueOf(jBaZenbakitzailea.getText()));
            zatBakoitia.setIzendatzailea(Integer.valueOf(jBaIzendatzailea.getText()));
            
            //jBaHarmartarBalioa.setText((String.format("%.2f", zatBakoitia.hamartarBaliokidea())) + " bolo / jaurtiketa");
            
        } else {
            jMensajeComprobacionBa.setText("Txarto!...Birpasatu eta saiatu berriro.");
        }
        
        //jBaHarmartarBalioa.setText(text);
        
    }//GEN-LAST:event_jComprobarBakoitiActionPerformed

    private void jComprobarBikoitiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComprobarBikoitiActionPerformed
        
        //se mostrará un mensaje emergente si el usuario no ha rellenado/definido alguno de los componentes de la fracción de números PARES
        if (jBiZenbakitzailea.getText().equals("") || jBiIzendatzailea.getText().equals("")) {JOptionPane.showMessageDialog(null,"Dirudienez, zenbaki bakoitien zatiki hau ez dago guztiz sortuta. \nBete itzazu eskatzen diren zatikiaren osagai guztiak.", "Errorea",JOptionPane.WARNING_MESSAGE);}
        
        
        //comprobar si la función 2 (PARES) está formada por números PARES
        if (Integer.valueOf(jBiZenbakitzailea.getText()) % 2 == 0) {
            jBiCheckedZenba.setText("✔");
        } else {
            jBiCheckedZenba.setText("✖");
        }

        if (Integer.valueOf(jBiIzendatzailea.getText()) % 2 == 0) {
            jBiCheckedIzenda.setText("✔");
        } else {
            jBiCheckedIzenda.setText("✖");
        }

        if (jBiCheckedZenba.getText() == "✔" && jBiCheckedIzenda.getText() == "✔") {
            
            jMensajeComprobacionBi.setText("Ondo!! Zatiki honek balio egokiak ditu.");
            
            zatBikoitia.setZenbakitzailea(Integer.valueOf(jBiZenbakitzailea.getText()));
            zatBikoitia.setIzendatzailea(Integer.valueOf(jBiIzendatzailea.getText()));
            
            //jBiHarmartarBalioa.setText((String.format("%.2f", zatBikoitia.hamartarBaliokidea())) + " bolo / jaurtiketa");
            
        } else {
            jMensajeComprobacionBi.setText("Txarto!...Birpasatu eta saiatu berriro.");
        }

    }//GEN-LAST:event_jComprobarBikoitiActionPerformed

    private void jBaZenbakitzaileaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaZenbakitzaileaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBaZenbakitzaileaActionPerformed

    private void jBaIzendatzaileaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaIzendatzaileaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBaIzendatzaileaActionPerformed

    private void jBiZenbakitzaileaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBiZenbakitzaileaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBiZenbakitzaileaActionPerformed

    private void jBiIzendatzaileaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBiIzendatzaileaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBiIzendatzaileaActionPerformed

    private void jEragiketaMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEragiketaMultiActionPerformed

        //esto hace que si pulsamos el botón "X", los demás se queden en blanco; queriendo decir que el que esté visible será el utilizado.
        //ademas, si no se cumplen las condiciones solicitadas para cada una de las fracciones, aparecerá una notificación emergente, diciendo que antes de realizar operaciones, debemos
        //crear correctamente cada una de las fracciones.
        if (jMensajeComprobacionBa.getText() == "Ondo!! Zatiki honek balio egokiak ditu." && jMensajeComprobacionBi.getText() == "Ondo!! Zatiki honek balio egokiak ditu.") {
            jEragiketaSuma.setText(" ");
            jEragiketaResta.setText(" ");
        } else if (jMensajeComprobacionBa.getText() == "Txarto!...Birpasatu eta saiatu berriro." || jMensajeComprobacionBi.getText() != "Txarto!...Birpasatu eta saiatu berriro.") {
            //notificacion emergente
            JOptionPane.showMessageDialog(null,"Mesedez, eragiketekin joan aurretik \nkonprobatu sarturiko balioak egokiak diren!", "Error",JOptionPane.WARNING_MESSAGE);
        } else if (jMensajeComprobacionBa.getText() == " " || jMensajeComprobacionBi.getText() == " ") {
            JOptionPane.showMessageDialog(null,"Oraindik ez! \nSakatu " + "Zuzena da?" + "botoia, sarturiko balioak egokiak diren hala ez jakiteko.", "Error",JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_jEragiketaMultiActionPerformed

    private void jEragiketaSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEragiketaSumaActionPerformed

        //esto hace que si pulsamos el botón "+", los demás se queden en blanco; queriendo decir que el que esté visible será el utilizado.
        //ademas, si no se cumplen las condiciones solicitadas para cada una de las fracciones, aparecerá una notificación emergente, diciendo que antes de realizar operaciones, debemos
        //crear correctamente cada una de las fracciones.
        if (jMensajeComprobacionBa.getText() == "Ondo!! Zatiki honek balio egokiak ditu." && jMensajeComprobacionBi.getText() == "Ondo!! Zatiki honek balio egokiak ditu.") {
            jEragiketaMulti.setText(" ");
            jEragiketaResta.setText(" ");
        } else if (jMensajeComprobacionBa.getText() == "Txarto!...Birpasatu eta saiatu berriro." || jMensajeComprobacionBi.getText() != "Txarto!...Birpasatu eta saiatu berriro.") {
            //notificacion emergente
            JOptionPane.showMessageDialog(null,"Mesedez, eragiketekin joan aurretik \nkonprobatu sarturiko balioak egokiak diren!", "Error",JOptionPane.WARNING_MESSAGE);
        } else if (jMensajeComprobacionBa.getText() == " " || jMensajeComprobacionBi.getText() == " ") {
            JOptionPane.showMessageDialog(null,"Oraindik ez! \nSakatu " + "Zuzena da?" + "botoia, sarturiko balioak egokiak diren hala ez jakiteko.", "Error",JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_jEragiketaSumaActionPerformed

    private void jEragiketaRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEragiketaRestaActionPerformed
        
        //esto hace que si pulsamos el botón "", los demás se queden en blanco; queriendo decir que el que esté visible será el utilizado.
        //ademas, si no se cumplen las condiciones solicitadas para cada una de las fracciones, aparecerá una notificación emergente, diciendo que antes de realizar operaciones, debemos
        //crear correctamente cada una de las fracciones.
        if (jMensajeComprobacionBa.getText() == "Ondo!! Zatiki honek balio egokiak ditu." && jMensajeComprobacionBi.getText() == "Ondo!! Zatiki honek balio egokiak ditu.") {
            jEragiketaMulti.setText(" ");
            jEragiketaSuma.setText(" ");
        } else if (jMensajeComprobacionBa.getText() == "Txarto!...Birpasatu eta saiatu berriro." || jMensajeComprobacionBi.getText() != "Txarto!...Birpasatu eta saiatu berriro.") {
            //notificacion emergente
            JOptionPane.showMessageDialog(null,"Mesedez, eragiketekin joan aurretik \nkonprobatu sarturiko balioak egokiak diren!", "Error",JOptionPane.WARNING_MESSAGE);
        } else if (jMensajeComprobacionBa.getText() == " " || jMensajeComprobacionBi.getText() == " ") {
            JOptionPane.showMessageDialog(null,"Oraindik ez! \nSakatu " + "Zuzena da?" + "botoia, sarturiko balioak egokiak diren hala ez jakiteko.", "Error",JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_jEragiketaRestaActionPerformed

    private void jEmaitzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmaitzaActionPerformed
        if (jMensajeComprobacionBa.getText() == "Ondo!! Zatiki honek balio egokiak ditu." && jMensajeComprobacionBi.getText() == "Ondo!! Zatiki honek balio egokiak ditu.") {
            if ((jEragiketaMulti.getText() == "X") && (jEragiketaSuma.getText() == " " && jEragiketaResta.getText() == " ")) {
                zatBakoitia.setZenbakitzailea(Integer.valueOf(jBaZenbakitzailea.getText()));
                zatBakoitia.setIzendatzailea(Integer.valueOf(jBaIzendatzailea.getText()));

                zatBikoitia.setZenbakitzailea(Integer.valueOf(jBiZenbakitzailea.getText()));
                zatBikoitia.setIzendatzailea(Integer.valueOf(jBiIzendatzailea.getText()));

                Zatikia zat3 = Zatikia.biderkatu(zatBakoitia, zatBikoitia);
                jEmaitzaZenba.setText(Integer.toString(zat3.getZenbakitzailea()));
                jEmaitzaIzenda.setText(Integer.toString(zat3.getIzendatzailea()));
            }

            if ((jEragiketaSuma.getText() == "+") && (jEragiketaMulti.getText() == " " && jEragiketaResta.getText() == " ")) {
                zatBakoitia.setZenbakitzailea(Integer.valueOf(jBaZenbakitzailea.getText()));
                zatBakoitia.setIzendatzailea(Integer.valueOf(jBaIzendatzailea.getText()));

                zatBikoitia.setZenbakitzailea(Integer.valueOf(jBiZenbakitzailea.getText()));
                zatBikoitia.setIzendatzailea(Integer.valueOf(jBiIzendatzailea.getText()));

                Zatikia zat3 = Zatikia.batu(zatBakoitia, zatBikoitia);
                jEmaitzaZenba.setText(Integer.toString(zat3.getZenbakitzailea()));
                jEmaitzaIzenda.setText(Integer.toString(zat3.getIzendatzailea()));
            }

            if ((jEragiketaResta.getText() == "-") && (jEragiketaMulti.getText() == " " && jEragiketaSuma.getText() == " ")) {
                zatBakoitia.setZenbakitzailea(Integer.valueOf(jBaZenbakitzailea.getText()));
                zatBakoitia.setIzendatzailea(Integer.valueOf(jBaIzendatzailea.getText()));

                zatBikoitia.setZenbakitzailea(Integer.valueOf(jBiZenbakitzailea.getText()));
                zatBikoitia.setIzendatzailea(Integer.valueOf(jBiIzendatzailea.getText()));

                Zatikia zat3 = Zatikia.kenketa(zatBakoitia, zatBikoitia);
                jEmaitzaZenba.setText(Integer.toString(zat3.getZenbakitzailea()));
                jEmaitzaIzenda.setText(Integer.toString(zat3.getIzendatzailea()));
            }
            
            if (jEragiketaMulti.getText() == "X" && jEragiketaSuma.getText() == "+" && jEragiketaResta.getText() == "-") {
                JOptionPane.showMessageDialog(null,"Aukeratu eragiketa mota bat!");
            }
            
            jEragiketaMulti.setText("X");
            jEragiketaSuma.setText("+");
            jEragiketaResta.setText("-");

        } else if (jEragiketaMulti.getText() != " " && jEragiketaSuma.getText() != " " && jEragiketaResta.getText() != " ") {
            
            //jErrorEmaitza.setText("Mesedez, aukeratu eragiekta bat.");
            
        }
        //JOptionPane.showMessageDialog(null,"Mensaje mostrado", "ERROR",JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_jEmaitzaActionPerformed

    private void jEmaitzaIzendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmaitzaIzendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmaitzaIzendaActionPerformed

    private void jEmaitzaZenbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmaitzaZenbaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmaitzaZenbaActionPerformed

    private void jIrJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIrJuegoActionPerformed
        FrameJolasa v2 = new FrameJolasa(this, true);
        //this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        v2.setVisible(true);
        this.setVisible(true);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        
    }//GEN-LAST:event_jIrJuegoActionPerformed

    private void jBalioakEzabatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalioakEzabatuActionPerformed
        
        //poner en blanco las casillas que se utilizan para definir los datos de la fracción de números IMPARES.	
	jBaZenbakitzailea.setText("");
        jBaIzendatzailea.setText("");
        jMensajeComprobacionBa.setText(" "); //borrar el texto de comprobación de la fracción de números IMPARES
        
        //poner en blanco las casillas que se utilizan para definir los datos de la fracción de números PARES.
        jBiZenbakitzailea.setText("");
        jBiIzendatzailea.setText("");
        jMensajeComprobacionBi.setText(" "); //borrar el texto de comprobación de la fracción de números PARES
        
        //poner en blanco las casillas que mostrarán la respuesta de la operación que se haya realizado
        jEmaitzaZenba.setText("");
        jEmaitzaIzenda.setText("");
        
        //bakoitia -> poner en blanco los label que muestran los símbolos "✔" y "✖"
        jBaCheckedZenba.setText(" ");
        jBaCheckedIzenda.setText(" ");
        
        //bikoitia -> poner en blanco los label que muestran los símbolos "✔" y "✖"
        jBiCheckedZenba.setText(" ");
        jBiCheckedIzenda.setText(" ");
        
        //restablecer los valores iniciales de los botones que se encargan de determinar el tipo de operación a realizar.
        //jEragiketaSuma.setText("+");
        //jEragiketaMulti.setText("X");
        //jEragiketaResta.setText("-");
        
    }//GEN-LAST:event_jBalioakEzabatuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAsmatuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAsmatuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAsmatuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAsmatuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAsmatuta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jBaCheckedIzenda;
    public static javax.swing.JLabel jBaCheckedZenba;
    private javax.swing.JLabel jBaHarmartarBalioa;
    public static javax.swing.JTextField jBaIzendatzailea;
    public static javax.swing.JLabel jBaZatikiEragiketak;
    public static javax.swing.JTextField jBaZenbakitzailea;
    public static javax.swing.JLabel jBakoitiak;
    private javax.swing.JButton jBalioakEzabatu;
    public static javax.swing.JLabel jBiChecked;
    public static javax.swing.JLabel jBiCheckedIzenda;
    public static javax.swing.JLabel jBiCheckedZenba;
    private javax.swing.JLabel jBiHarmartarBalioa;
    public static javax.swing.JTextField jBiIzendatzailea;
    public static javax.swing.JTextField jBiZenbakitzailea;
    public static javax.swing.JLabel jBikoitiak;
    public static javax.swing.JButton jComprobarBakoiti;
    public static javax.swing.JButton jComprobarBikoiti;
    public static javax.swing.JButton jEmaitza;
    public static javax.swing.JTextField jEmaitzaIzenda;
    public static javax.swing.JTextField jEmaitzaZenba;
    public static javax.swing.JLabel jEragiketaIzenburua;
    public static javax.swing.JButton jEragiketaMulti;
    public static javax.swing.JButton jEragiketaResta;
    public static javax.swing.JButton jEragiketaSuma;
    public static javax.swing.JLabel jErrorEmaitza;
    public static javax.swing.JButton jIrJuego;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jMensajeComprobacionBa;
    public static javax.swing.JLabel jMensajeComprobacionBi;
    public static javax.swing.JSeparator jSeparator1;
    public static javax.swing.JSeparator jSeparator2;
    public static javax.swing.JSeparator jSeparator3;
    public static javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
